package flota.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * TgfRol generated by hbm2java
 */
public class TgfRol implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idRol;
	private String rolNombre;
	private Set tgfPersonas = new HashSet(0);

	public TgfRol() {
	}

	public TgfRol(long idRol, String rolNombre) {
		this.idRol = idRol;
		this.rolNombre = rolNombre;
	}

	public TgfRol(long idRol, String rolNombre, Set tgfPersonas) {
		this.idRol = idRol;
		this.rolNombre = rolNombre;
		this.tgfPersonas = tgfPersonas;
	}

	public long getIdRol() {
		return this.idRol;
	}

	public void setIdRol(long idRol) {
		this.idRol = idRol;
	}

	public String getRolNombre() {
		return this.rolNombre;
	}

	public void setRolNombre(String rolNombre) {
		this.rolNombre = rolNombre;
	}

	public Set getTgfPersonas() {
		return this.tgfPersonas;
	}

	public void setTgfPersonas(Set tgfPersonas) {
		this.tgfPersonas = tgfPersonas;
	}

}
